# Generated by Django 4.2.1 on 2024-06-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_of_era', models.DateField(blank=True, null=True)),
                ('end_of_era', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('capital', models.CharField(max_length=64)),
                ('population', models.IntegerField()),
                ('income', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='country_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('impact_economy', models.FloatField(default=0.0)),
                ('impact_society', models.FloatField(default=0.0)),
                ('impact_military', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='factory_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='admin_panel.country')),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Trwająca'), ('ended', 'Zakończona')], default='ongoing', max_length=20)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_started', to='admin_panel.country')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_defended', to='admin_panel.country')),
            ],
        ),
        migrations.CreateModel(
            name='TradeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_agreements', to='admin_panel.alliance')),
                ('participants', models.ManyToManyField(related_name='trade_agreements', to='admin_panel.country')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='admin_panel.country')),
                ('imports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='admin_panel.country')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.resources')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('efficiency_production', models.FloatField(default=1.0)),
                ('efficiency_trade', models.FloatField(default=1.0)),
                ('efficiency_military', models.FloatField(default=1.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='technology_image')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age', to='admin_panel.age')),
            ],
        ),
        migrations.CreateModel(
            name='SocialDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_rate', models.FloatField(default=0.0)),
                ('public_health_index', models.FloatField(default=0.0)),
                ('education_index', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_development_image/')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_development', to='admin_panel.country')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='required_resources_images/')),
                ('required_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_resources', to='admin_panel.resources')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_resources', to='admin_panel.resources')),
            ],
        ),
        migrations.CreateModel(
            name='PeaceTreaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('country1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peace_treaties_as_country1', to='admin_panel.country')),
                ('country2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peace_treaties_as_country2', to='admin_panel.country')),
            ],
        ),
        migrations.CreateModel(
            name='Ecology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_quality', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('water_pollution', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('forest_coverage', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('wildlife_population', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecology', to='admin_panel.country')),
            ],
        ),
        migrations.CreateModel(
            name='BuildFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required_resource_1', models.IntegerField()),
                ('quantity_required_resource_2', models.IntegerField()),
                ('quantity_required_resource_3', models.IntegerField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.age')),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='build_factory', to='admin_panel.factory')),
                ('required_resource_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_factory_resource_1', to='admin_panel.resources')),
                ('required_resource_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_factory_resource_2', to='admin_panel.resources')),
                ('required_resource_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_factory_resource_3', to='admin_panel.resources')),
                ('resources_production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.requiredresources')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('power', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('quantity_1', models.IntegerField()),
                ('quantity_2', models.IntegerField()),
                ('quantity_3', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='army_image/')),
                ('country', models.ManyToManyField(related_name='army', to='admin_panel.country')),
                ('required_resources_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_resources_1', to='admin_panel.resources')),
                ('required_resources_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_resources_2', to='admin_panel.resources')),
                ('required_resources_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_resources_3', to='admin_panel.resources')),
            ],
        ),
        migrations.AddField(
            model_name='alliance',
            name='member_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_member_1', to='admin_panel.country'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='member_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_member_2', to='admin_panel.country'),
        ),
    ]
