# Generated by Django 4.2.1 on 2024-06-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources_image/'),
        ),
    ]
