# Generated by Django 4.2.1 on 2024-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_resources_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='efficiency_military',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='technology',
            name='efficiency_production',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='technology',
            name='efficiency_trade',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
