# Generated by Django 4.2.1 on 2024-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_technology_efficiency_military_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='impact_economy',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='impact_military',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='impact_society',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='socialdevelopment',
            name='education_index',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='socialdevelopment',
            name='poverty_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='socialdevelopment',
            name='public_health_index',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
