# Generated by Django 4.2.1 on 2024-06-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_event_impact_economy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialdevelopment',
            name='country',
        ),
    ]
