# Generated by Django 5.0.7 on 2024-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_ecology_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecology',
            name='image_air_quality',
            field=models.ImageField(blank=True, null=True, upload_to='ecology_images/'),
        ),
        migrations.AddField(
            model_name='ecology',
            name='image_forest_coverage',
            field=models.ImageField(blank=True, null=True, upload_to='ecology_images/'),
        ),
        migrations.AddField(
            model_name='ecology',
            name='image_water_pollution',
            field=models.ImageField(blank=True, null=True, upload_to='ecology_images/'),
        ),
        migrations.AddField(
            model_name='ecology',
            name='image_wildlife_population',
            field=models.ImageField(blank=True, null=True, upload_to='ecology_images/'),
        ),
    ]
