# Generated by Django 5.0.7 on 2024-09-30 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_ecology_image_air_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='factory',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.resources'),
        ),
    ]
