# Generated by Django 5.0.7 on 2024-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_factory_quantity_factory_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background_age_image/'),
        ),
    ]
