# Generated by Django 5.0.7 on 2024-11-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_age_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='background',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='background_age_image/'),
        ),
        migrations.AlterField(
            model_name='age',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='age_image/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='country_image/'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='factory_image/'),
        ),
        migrations.AlterField(
            model_name='requiredresources',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='required_resources_images/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='resources_image/'),
        ),
    ]
