# Generated by Django 5.0.7 on 2024-11-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_buildfactory_technology_factory_technology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='country',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='resources',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='CountryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_resources', to='admin_panel.country')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_resources', to='admin_panel.resources')),
            ],
        ),
    ]
