# Generated by Django 5.0.7 on 2025-01-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_countryresource_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='resources_to_unlock', to='admin_panel.resources'),
        ),
    ]
