# Generated by Django 5.0.7 on 2025-01-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_technology_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='vailable',
            field=models.BooleanField(default=False),
        ),
    ]
