# Generated by Django 5.0.7 on 2025-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_technology_vailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='resources',
        ),
        migrations.AddField(
            model_name='technology',
            name='quantyti_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='quantyti_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='quantyti_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='resource_1',
            field=models.ManyToManyField(blank=True, related_name='resources_to_unlock_1', to='admin_panel.resources'),
        ),
        migrations.AddField(
            model_name='technology',
            name='resource_2',
            field=models.ManyToManyField(blank=True, related_name='resources_to_unlock_2', to='admin_panel.resources'),
        ),
        migrations.AddField(
            model_name='technology',
            name='resource_3',
            field=models.ManyToManyField(blank=True, related_name='resources_to_unlock_3', to='admin_panel.resources'),
        ),
    ]
