# Generated by Django 5.0.7 on 2025-01-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_remove_technology_resources_technology_quantyti_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='quantyti_1',
            new_name='quantity_1',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='quantyti_2',
            new_name='quantity_2',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='quantyti_3',
            new_name='quantity_3',
        ),
    ]
