# Generated by Django 5.0.7 on 2025-01-09 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_rename_quantyti_1_technology_quantity_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='resource_1',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='resource_2',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='resource_3',
        ),
        migrations.AddField(
            model_name='technology',
            name='resource_1',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources_to_unlock_1', to='admin_panel.resources'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='resource_2',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources_to_unlock_2', to='admin_panel.resources'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='resource_3',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources_to_unlock_3', to='admin_panel.resources'),
            preserve_default=False,
        ),
    ]
