# Generated by Django 5.0.7 on 2025-01-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_remove_technology_resource_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='time_to_unlock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
