# Generated by Django 5.0.7 on 2025-01-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_technology_time_to_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='type',
            field=models.CharField(blank=True, choices=[('ARMY', 'Wojskowa'), ('ECONOMY', 'Gospodarcza'), ('SOCIETY', 'Społeczna'), ('SCIENCE', 'Naukowa'), ('CULTURE', 'Kulturowa'), ('OTHER', 'Inna')], max_length=20, null=True),
        ),
    ]
