# Generated by Django 5.0.7 on 2025-02-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_technology_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='vailable',
        ),
    ]
