# Generated by Django 4.2.1 on 2024-05-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_of_era', models.DateField(blank=True, null=True)),
                ('end_of_era', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('capital', models.CharField(max_length=64)),
                ('population', models.IntegerField(max_length=64)),
                ('income', models.IntegerField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('impact_economy', models.FloatField(default=0.0)),
                ('impact_society', models.FloatField(default=0.0)),
                ('impact_military', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Trwająca'), ('ended', 'Zakończona')], default='ongoing', max_length=20)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_started', to='game.country')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_defended', to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='TradeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_agreements', to='game.alliance')),
                ('participants', models.ManyToManyField(related_name='trade_agreements', to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='game.country')),
                ('imports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='game.country')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.resources')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('efficiency_production', models.FloatField(default=1.0)),
                ('efficiency_trade', models.FloatField(default=1.0)),
                ('efficiency_military', models.FloatField(default=1.0)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age', to='game.age')),
            ],
        ),
        migrations.CreateModel(
            name='SocialDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_rate', models.FloatField(default=0.0)),
                ('public_health_index', models.FloatField(default=0.0)),
                ('education_index', models.FloatField(default=0.0)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_development', to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('required_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_resources', to='game.resources')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_resources', to='game.resources')),
            ],
        ),
        migrations.CreateModel(
            name='PeaceTreaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('country1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peace_treaties_as_country1', to='game.country')),
                ('country2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peace_treaties_as_country2', to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='Ecology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_quality', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('water_pollution', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('forest_coverage', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('wildlife_population', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecology', to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='BuildFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.age')),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='build_factory', to='game.factory')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.resources')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('power', models.IntegerField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='army', to='game.country')),
            ],
        ),
        migrations.AddField(
            model_name='alliance',
            name='members',
            field=models.ManyToManyField(related_name='alliances', to='game.country'),
        ),
    ]
