# Generated by Django 5.0.7 on 2024-11-29 10:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0015_alter_countryresource_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='admin_panel.age')),
                ('alliances', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.alliance')),
                ('armies', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.army')),
                ('build_factories', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.buildfactory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='admin_panel.country')),
                ('ecology', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='admin_panel.ecology')),
                ('events', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.event')),
                ('peace_treaties', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.peacetreaty')),
                ('required_resources', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.requiredresources')),
                ('social_development', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='admin_panel.socialdevelopment')),
                ('technologies', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.technology')),
                ('trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='admin_panel.trade')),
                ('trade_agreements', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.tradeagreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to=settings.AUTH_USER_MODEL)),
                ('wars', models.ManyToManyField(blank=True, related_name='worlds', to='admin_panel.war')),
            ],
        ),
        migrations.CreateModel(
            name='NewWorldFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.factory')),
                ('new_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.newworld')),
            ],
        ),
        migrations.AddField(
            model_name='newworld',
            name='factories',
            field=models.ManyToManyField(blank=True, related_name='worlds', through='game.NewWorldFactory', to='admin_panel.factory'),
        ),
        migrations.CreateModel(
            name='NewWorldResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('new_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.newworld')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.resources')),
            ],
        ),
        migrations.AddField(
            model_name='newworld',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='worlds', through='game.NewWorldResource', to='admin_panel.resources'),
        ),
    ]
