# Generated by Django 4.2.1 on 2024-05-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(),
        ),
    ]
