# Generated by Django 4.2.1 on 2024-06-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArmyResourceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='game.army')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army_requirements', to='game.resources')),
            ],
            options={
                'unique_together': {('army', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='army',
            name='required_resources',
            field=models.ManyToManyField(related_name='armies', through='game.ArmyResourceRequirement', to='game.resources'),
        ),
    ]
