# Generated by Django 4.2.1 on 2024-06-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_army_defense_armyresourcerequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='required_resources',
        ),
        migrations.AddField(
            model_name='army',
            name='quantity_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='army',
            name='quantity_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='army',
            name='quantity_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='army',
            name='required_resources_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_resources_1', to='game.resources'),
        ),
        migrations.AddField(
            model_name='army',
            name='required_resources_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_resources_2', to='game.resources'),
        ),
        migrations.AddField(
            model_name='army',
            name='required_resources_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_resources_3', to='game.resources'),
        ),
        migrations.DeleteModel(
            name='ArmyResourceRequirement',
        ),
    ]
