# Generated by Django 4.2.1 on 2024-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_country_income_alter_country_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='country',
        ),
        migrations.AddField(
            model_name='resources',
            name='country',
            field=models.ManyToManyField(related_name='resources', to='game.country'),
        ),
    ]
