# Generated by Django 5.0.7 on 2025-02-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_remove_technology_vailable'),
        ('game', '0002_remove_newworld_ecology_newworld_ecology'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWorldTechology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.BooleanField(default=False)),
                ('new_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.newworld')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.technology')),
            ],
        ),
    ]
