# Generated by Django 4.2.1 on 2024-06-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_army_required_resources_army_quantity_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='country',
        ),
        migrations.AddField(
            model_name='army',
            name='country',
            field=models.ManyToManyField(related_name='army', to='game.country'),
        ),
    ]
