# Generated by Django 5.0.7 on 2024-09-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_newworld_resources_alter_newworld_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworld',
            name='resources',
        ),
    ]
