# Generated by Django 4.2.1 on 2024-05-19 12:41

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_resources_country_resources_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='image',
            field=models.ImageField(null=True, upload_to=game.models.factory_image_upload_path),
        ),
    ]
