# Generated by Django 5.0.7 on 2025-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_newworld_unlocking_technology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworld',
            name='unlocking_technology',
        ),
        migrations.AddField(
            model_name='newworldtechology',
            name='unlocking_technology',
            field=models.BooleanField(default=False),
        ),
    ]
