# Generated by Django 5.0.7 on 2025-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_newworld_unlocking_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworldtechology',
            name='time_to_unlock',
            field=models.DateField(blank=True, null=True),
        ),
    ]
