# Generated by Django 4.2.1 on 2024-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_factory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
