# Generated by Django 4.2.1 on 2024-05-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_resources_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildfactory',
            name='resources',
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='required_resource',
            field=models.ManyToManyField(to='game.resources'),
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='resources_production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.requiredresources'),
        ),
    ]
