# Generated by Django 5.0.7 on 2025-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_newworldtechology_time_to_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworldtechology',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
