# Generated by Django 4.2.1 on 2024-05-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_buildfactory_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildfactory',
            name='required_resource',
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='quantity_required_resource_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='quantity_required_resource_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='quantity_required_resource_3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='required_resource_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='build_factory_resource_1', to='game.resources'),
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='required_resource_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='build_factory_resource_2', to='game.resources'),
        ),
        migrations.AddField(
            model_name='buildfactory',
            name='required_resource_3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='build_factory_resource_3', to='game.resources'),
        ),
    ]
