# Generated by Django 5.0.7 on 2024-09-19 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_newworld_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworld',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
