# Generated by Django 5.0.7 on 2024-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_factory_quantity_factory_resource'),
        ('game', '0008_newworld_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworld',
            name='build_factory',
        ),
        migrations.RemoveField(
            model_name='newworld',
            name='resources',
        ),
        migrations.AddField(
            model_name='newworld',
            name='build_factory',
            field=models.ManyToManyField(blank=True, related_name='world_build_factories', to='admin_panel.buildfactory'),
        ),
        migrations.AddField(
            model_name='newworld',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='world_resources', to='admin_panel.resources'),
        ),
    ]
