# Generated by Django 5.0.7 on 2024-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_backpack_backpackresource_backpack_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackresource',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
